flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: v1.0.0
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: v1.0.0
extra-deps:
  - s-cargot-0.1.0.0
resolver: lts-7.18
